version: "3.9"

services:
  host:
    container_name: postgres_test
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=test"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
