#
# Blog
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      role: blog
  template:
    metadata:
      labels:
        role: blog
    spec:
      containers:
      - name: blog
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        # env:
        # - name: TEST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: blog
        #       key: test
        # - name:  USER_TEST
        #   valueFrom:
        #     secretKeyRef:
        #       name: blog
        #       key: user_test


---
#
# API_Blog
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api-blog
  template:
    metadata:
      labels:
        role: api-blog
    spec:
      containers:
      - name: api-blog
        image: barckcode/api_blog:1.0
        ports:
        - containerPort: 8000
        env:
        # - name: TEST_API
        #   valueFrom:
        #     configMapKeyRef:
        #       name: blog
        #       key: test_api
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_host
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_password


---
#
# Blog SVC
###
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - port:  80
    targetPort:  80
  selector:
    role: blog


---
#
# API_Blog SVC
###
apiVersion: v1
kind: Service
metadata:
  name: api-blog
spec:
  ports:
  - port:  80
    targetPort:  8000
  selector:
    role: api-blog
