---
#####
# SSH RSA:
#####
ssh_key_path: /ansible/conf/private/ssh/aws_id_rsa


#####
# Config System Users:
#####
www_users:
  - admin


#####
# List of apt packages to install:
#####
list_additional_pkg:
  - git-all
  - nginx

#####
# Vhosts:
#####
# Paths ansible conf:
src_vhosts_path: /ansible/conf/web/vhosts
# src_private_files_path: /ansible/conf/web/private

symbolic_link_vhost:
  - helmcode_com.conf
  - pre_helmcode_com.conf
  - rick-and-morty_helmcode_com.conf
  - weather_helmcode_com.conf
  - web-infographics_helmcode_com.conf

root_dir_vhost:
  - helmcode_com
