version: "3.9"

services:
  social_network_bot:
    container_name: social_network_bot
    build:
      context: ../../../social_network_bot
      dockerfile: Dockerfile.local
    command: python main.py
    volumes:
      - ../../../social_network_bot/app:/app
    env_file:
      - ./app.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 8000:8000
    networks:
      - social_network_bot_net

networks:
  social_network_bot_net:
