---
- name: Create scripts directories
  file:
    path: "/home/admin/deploy/{{ application }}/scripts/"
    owner: admin
    group: admin
    state: directory
    mode: 0775

- name: Copy scripts with owner and permissions
  copy:
    src: "{{ item }}"
    dest: "/home/admin/deploy/{{ application }}/scripts/"
    owner: admin
    group: admin
    mode: 0774
  with_fileglob:
    - "/ansible/conf/deploy/{{ application }}/scripts/*"
