---
- name: Copy scripts with owner and permissions
  copy:
    src: "{{ item }}"
    dest: "/home/admin/repository/{{ repository_dir }}/{{ application }}/deploy/"
    owner: admin
    group: admin
    mode: 0774
  with_fileglob:
    - "/ansible/conf/deploy/{{ application }}/scripts/*"
