---
- name: Add apt key
  shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -


- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com stretch main


- name: Install waypoint
  apt:
    update_cache: yes
    state: latest
    pkg:
    - waypoint
