---
- name: Install aptitude using apt
  apt:
    update_cache: yes
    state: latest
    force_apt_get: yes
    pkg:
    - aptitude

- name: Install required system packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python3-setuptools

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    state: latest
    pkg:
    - docker-ce

- name: Install Docker Module for Python
  pip:
    name: docker
    executable: /usr/bin/pip3

- name: Download Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create a symbolic link
  # shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  file:
    src: "/usr/local/bin/docker-compose"
    dest: "/usr/bin/docker-compose"
    state: link
