---
- name: Copying vhosts files with owner and permissions
  copy:
    src: "{{ item }}"
    dest: "{{ dest_vhosts_available_path }}/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ src_vhosts_path }}/*"
  when: src_vhosts_path is defined

- name: Create a symbolic link of vhosts
  file:
    src: "{{ dest_vhosts_available_path }}/{{ item }}"
    dest: "{{ dest_vhosts_enabled_path }}/{{ item }}"
    owner: root
    group: root
    state: link
  loop: "{{ symbolic_link_vhost }}"
  when: symbolic_link_vhost is defined

- name: Create vhosts directories
  file:
    path: "/var/www/{{ item }}"
    owner: admin
    group: www-data
    state: directory
  loop: "{{ root_dir_vhost }}"
  when: root_dir_vhost is defined

# - name: Copy of private files
#   copy:
#     src: "{{ item.prod_env }}"
#     dest: "/var/www/{{ item.prod_vhost }}/"
#     owner: root
#     group: root
#     mode: 0644
#   loop:
#     - { prod_env: "{{ src_private_files_path }}/prod.env",  prod_vhost: 'helmcode.com' }
#     - { prod_env: "{{ src_private_files_path }}/test.env",  prod_vhost: 'pre_helmcode.com' }

- name: Restart ngnix
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
