#
# Blog
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      role: blog
  template:
    metadata:
      labels:
        role: blog
    spec:
      containers:
      - name: blog
        image: barckcode/flask_blog:2.3
        ports:
        - containerPort: 5000
        env:
        # ConfigMap
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: blog
              key: flask_app
        - name:  FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: blog
              key: flask_env
        # SecretKey
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_host
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_password
        - name: SECRET_KEY_FORM
          valueFrom:
            secretKeyRef:
              name: blog
              key: secret_key_form
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: blog
              key: bot_token
        - name: CHAT_ID
          valueFrom:
            secretKeyRef:
              name: blog
              key: chat_id


---
#
# API_Blog
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api-blog
  template:
    metadata:
      labels:
        role: api-blog
    spec:
      containers:
      - name: api-blog
        image: barckcode/api_blog:2.0
        ports:
        - containerPort: 8000
        env:
        # ConfigMap
        - name: TOKEN_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: blog
              key: token_expiration
        # SecretKey
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_host
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog
              key: db_password
        - name: TOKEN_SSL
          valueFrom:
            secretKeyRef:
              name: blog
              key: token_ssl
        - name: TOKEN_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: blog
              key: token_algorithm


---
#
# Blog SVC
###
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - port:  80
    targetPort:  5000
  selector:
    role: blog


---
#
# API_Blog SVC
###
apiVersion: v1
kind: Service
metadata:
  name: api-blog
spec:
  ports:
  - port:  80
    targetPort:  8000
  selector:
    role: api-blog
