---
############################# TAGS FOR TASKS #############################
# test                  - Test
# config_deploy         - Config env to deploy
# install_ansible       - Install Ansible
# install_apt_packages  - Install packages whit apt
# install_docker        - Install Docker and docker-compose for debian
# install_jenkins       - Install Jenkins
# install_mysql         - Install Percona Server for MySQL
# nginx_vhosts          - Configure vhosts
# ssh_rsa               - Copy SSH KEY RSA file
# set_hostname          - Set a hostname
# system_users          - Config System Users
##########################################################################
######################## Hosts:
#- hosts: sauron
#- hosts: web01
#- hosts: bbdd01
######################## Groups:
#- hosts: global
#- hosts: blog
#- hosts: swarm
#- hosts: web
#- hosts: bbdd

  tasks:
    - include: tasks/test.yml
      tags:
        - test

    - include: tasks/copy_tmp_files.yml
      tags:
        - copy_tmp_files

    - include: tasks/config_deploy.yml
      tags:
        - config_deploy

    - include: tasks/install_ansible.yml
      tags:
        - install_ansible

    - include: tasks/install_apt_packages.yml
      tags:
        - install_apt_packages

    - include: tasks/install_docker.yml
      tags:
        - install_docker

    - include: tasks/install_jenkins.yml
      tags:
        - install_jenkins

    - include: tasks/install_mysql.yml
      tags:
        - install_mysql

    - include: tasks/nginx_vhosts.yml
      tags:
        - nginx_vhosts

    - include: tasks/ssh_rsa.yml
      tags:
        - ssh_rsa

    - include: tasks/set_hostname.yml
      tags:
        - set_hostname

    - include: tasks/system_users.yml
      tags:
        - system_users
